### ISSUE TITLE
Not able to install SC.

### ISSUE THREAD

**Issue by iiCarelessness** [dialtoneuk/Syscrack#10]
```
Critical Error
@ C:\xampp\htdocs\src\Application\Settings.php line 335
An error occurred outside of the framework, this is usually due to a permission error, a rewrite error, or something completely different, check out the error stack below.

    #0 C:\xampp\htdocs\src\Application\Settings.php(172): Framework\Application\Settings::loadSettings()
#1 [internal function]: Framework\Application\Settings::preloadSettings()
#2 C:\xampp\htdocs\src\Application\Loader.php(71): forward_static_call(Array)
#3 C:\xampp\htdocs\src\Application\Loader.php(32): Framework\Application\Loader->loadPaypload()
#4 C:\xampp\htdocs\src\Application.php(147): Framework\Application\Loader->__construct(NULL)
#5 C:\xampp\htdocs\src\Application.php(59): Framework\Application->createLoader()
#6 C:\xampp\htdocs\src\Application.php(41): Framework\Application->initialize()
#7 C:\xampp\htdocs\index.php(240): Framework\Application->__construct(false)
#8 {main}
```

**Comment by iiCarelessness** [comment]
Also you should get a new Discord. :)

**Comment by dialtoneuk** [comment]
This looks like a permission error to me.  Could you please use the issue template provided in the githubs root directory and state what operating system you are running from?

**Comment by bornhaeusser** [comment]
same to me on synology

Critical Error
@ xxxxxxxxxxxxxxxxxxx/src/Application/Settings.php line 335
An error occurred outside of the framework, this is usually due to a permission error, a rewrite error, or something completely different, check out the error stack below.

    #0 /volume1/web/game/hacking/src/Application/Settings.php(172): Framework\Application\Settings::loadSettings()
#1 [internal function]: Framework\Application\Settings::preloadSettings()
#2 /volume1/web/game/hacking/src/Application/Loader.php(71): forward_static_call(Array)
#3 /volume1/web/game/hacking/src/Application/Loader.php(32): Framework\Application\Loader->loadPaypload()
#4 /volume1/web/game/hacking/src/Application.php(147): Framework\Application\Loader->__construct(NULL)
#5 /volume1/web/game/hacking/src/Application.php(59): Framework\Application->createLoader()
#6 /volume1/web/game/hacking/src/Application.php(41): Framework\Application->initialize()
#7 /volume1/web/game/hacking/index.php(240): Framework\Application->__construct(false)
#8 {main}

**Comment by dialtoneuk** [comment]
This to me seems like a pretty standard permissions error which normally occurs on linux based systems. Simply run the following bash terminal command to chmod your data folder which should allow the PHP IO module to correctly read and write.

`
sudo chmod -R 777 /var/www/html/
`

If that doesn't work, instead please check your syscracks root folder and hop into /data/config/ and check for a settings file.

**Comment by bornhaeusser** [comment]
permissions are right. 
settings.json is there

i have installed it in a subfolder with an subdomain linked direkt into that.

**Comment by dialtoneuk** [comment]
Ahh.

I think your issue might be how Syscrack is parsing where its located when running it on a subdomain with any sort of dot in the folder. Its something I haven't gotten around to fixing as we've mostly been running syscracks on roots. What's your current directory set up with your web server?

**Comment by bornhaeusser** [comment]
/volume1/web/game/hacking/ "gamefiles in here"

**Comment by dialtoneuk** [comment]
Thank's for pointing this out. I've flagged it as an issue, I'm pretty sure I've fixed this in the latest push I'm about to commit as I recently changed how the settings work. For now, because of the way you are running Syscrack, I suggest heading into the following file in your text editor

`
src/Application/Settings.php
`

and then going down to line 386 where this function should be visible

`
private static function fileLocation()
	{

		return sprintf('%s' . DIRECTORY_SEPARATOR . 'data/config' . DIRECTORY_SEPARATOR . 'settings.json', $_SERVER['DOCUMENT_ROOT'] );
	}
`

and please check that it is correct for your system. You can give a hard path it doesn't matter.

**Comment by bornhaeusser** [comment]
i entered

`private static function fileLocation()
	{

		return sprintf('/volume1/web/game/hacking' . DIRECTORY_SEPARATOR . 'data/config' . DIRECTORY_SEPARATOR . 'settings.json', $_SERVER['DOCUMENT_ROOT'] );
	}`

right? but it does no changes to me

**Comment by dialtoneuk** [comment]
I think the problem might be that your document root isn't being set. So to fix this, change the following line you have entered to this instead

`
return '/volume1/web/game/hacking/data/config/settings.json'
`

and then, to make sure, head to your settings.json and edit the setting "filesystem_root" to instead equal 

`
'/volume1/web/game/hacking/
`

**Comment by bornhaeusser** [comment]
First changed:
`return '/volume1/web/game/hacking/data/config/settings.json';`

Second Changed:
`"filesystem_root": "\/volume1\/web\/game\/hacking",`

**Comment by dialtoneuk** [comment]
Let me know if it is still giving you errors, another method you could also try is to insert into the index.php the following code

`
$_SERVER['DOCUMENT_ROOT'] =" /volume1/web/game/hacking/"
`

**Comment by dialtoneuk** [comment]
I'd hold tight for the push I am about to commit. We are still in Alpha so we mostly only support officially Ubuntu and Windows and at very basic settings as we haven't spent a lot of time looking at these kind of issues yet and more or less focusing on getting out of Alpha first.

Feel free to try out the game on our official website, or revert to starting a fresh Ubuntu installation and follow our read me. I've noted your issue so it'll be hopefully fixed in the upcoming patch.

**Comment by iiCarelessness** [comment]
Currently on Windows atm, not Ubuntu as I wanted to try this out before getting an actual server to run on it with an official domain, you know?

I have no idea what's wrong tbh, as I can't do most of what you've said due to the commands/edits being to do with Linux.

**Comment by iiCarelessness** [comment]
### Expected Behavior



It should work properly.

### Current Behavior



Error I posted above.

### Possible Solution



I'm not sure.

### Steps to Reproduce (for bugs)



Follow the install steps for Windows, try localhost in your browser, then you'll get the error

### Context



### Your Environment

* Version used: Latest
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by dialtoneuk** [comment]
Fixed this in the latest patch, please reopen if continued issues after push

**Comment by bornhaeusser** [comment]
Now i am a bitt closer:

`@ /volume1/web/game/hacking/src/Application/Loader.php line 47
An error occurred outside of the framework, this is usually due to a permission error, a rewrite error, or something completely different, check out the error stack below.

    #0 /volume1/web/game/hacking/src/Application/Loader.php(32): Framework\Application\Loader->loadPaypload()
#1 /volume1/web/game/hacking/src/Application.php(147): Framework\Application\Loader->__construct(NULL)
#2 /volume1/web/game/hacking/src/Application.php(59): Framework\Application->createLoader()
#3 /volume1/web/game/hacking/src/Application.php(41): Framework\Application->initialize()
#4 /volume1/web/game/hacking/index.php(240): Framework\Application->__construct(false)
#5 {main}`

**Comment by dialtoneuk** [comment]
Do the same for your Loader.php, change the file it is trying to find with the hard location you set earlier,
